### ISSUE TITLE
How to run a training once the docker image is built?

### ISSUE THREAD

**Issue by IonaGuyomarch** [Seeed-Projects/jetson-examples#5]
Hey there,

First of all, thanks you so much for making this yolov10 support for Jetsons. Now here is my problem: I'm new with Docker, and even if I've achieved all installation steps, I don't get how I can run a prediction using the docker image and without using the local URL (http://127.0.0.1:7860). I've tried to run this command: 
`docker run -it --gpus all -v /path/to/my/models:/data yolov10-jetson`
But it just starts the local URL. 

I've already trained some models using my Windows machine but I would like to be able to do some predictions using my Jetson Xavier and my pre-trained models. 

Any advices?

**Comment by yuyoujiang** [comment]
Hi IonaGuyomarch, 

Thank you very much for your interest in Jetson and YOLOv10. 
The jetson-examples provide a convenient way to quickly experience YOLOv10 on Jetson.
If you want to use your own model, I think there are two implementation options:
1. Compile a new docker container. The prerequisite is that you need to spend some time learning about Docker. Here is the configuration file I used when compiling the container. 
https://github.com/Seeed-Projects/jetson-examples/blob/main/reComputer/scripts/yolov10/Dockerfile
2.  Follow these steps to install the necessary dependencies on Jetson: 
https://github.com/THU-MIG/yolov10?tab=readme-ov-file#installation 
Since the Jetson `ARM64` system, some dependencies might need to be recompiled before they can be installed.

**Comment by IonaGuyomarch** [comment]
Hi, 
Thanks a lot for these information! I'm going to learn more about docker then, I think that's what I need.
